### ISSUE TITLE
Modernize the codebase

### ISSUE THREAD

**Issue by bswck** [mkdocs-publisher/mkdocs-publisher#83]
### Feature description

Some general thoughts after flicking through the codebase, gathered in a "to-do":
- [ ] Drop legacy habits (stop using `OrderedDict` which was superseded by `dict` in 3.7 (technically 3.6) unless for `popitem`/`move_to_end`, stop using deprecated typing aliases)
- [ ] Improve logging (remove the entire untested logging boilerplate, probably could replace with a few lines of structlog/loguru, use deferred percent-style formatting instead of f-string based)
- [ ] Use `typing.TYPE_CHECKING` for types-only importing
- [ ] General quality (remove unnecessary casts, [unnecessary parentheses](https://docs.python.org/3/reference/expressions.html#operator-precedence))
- [ ] Definitely do not use regex for counting words in posts https://github.com/mkusz/mkdocs-publisher/blob/915913988311db9c94e92d18a094aab61ab9c59e/mkdocs_publisher/blog/parsers.py#L41-L61
- [ ] We really shouldn't be using `importlib.resources` in so many places

I can contribute to some of these when I find time, as well as find other rooms for improvement.
Thanks for extending the capabilities of MkDocs!

### Contact details

bartoszpiotrslawecki@gmail.com

**Comment by mkusz** [comment]
Hi @bswck and thanks for all the insights. Please take a look at my answers to yours comments:

1. `OrderedDict` will be removed in a near future when I will rewrite a whole blog plugin. The code base there is from a very early days of this entire repo when I was more learning how MkDocs works internally and it needs to be changed to allow for some other things to be added.`OrderedDict` will be removed in a near future when I will rewrite a whole blog plugin. The code base there is from a very early days of this entire repo when I was more learning how MkDocs works internally and it needs to be changed to allow for some other things to be added.
2. I have done some brief overview of proposed libs and I need to play with it a little bit. It seems like structlog can replace my code but I'm not fully sure if it will works like I wanted.
3. `typing.TYPE_CHECKING` wasn't aware of that trick. Definitely I will start using it.
4. In some cases some unnecessary parenthesise were added just to better "see" what is from where and group some things together. Without specific files/code lines is hard to guess what and why was added. Probably some of them where just not cleaned before push to the repo.
5. Entire function with regexp word counting is never used (it was left there for further use). I'm not sure why it shouldn't been used and you didn't proposed any better solution. In the future please put some additional explanation why this specific code is bad and what is proposed solution (like you did with logging).
6. I have checked and it seems like "importlib.resources" is used in `resources.py` and in some old blog files that will be rewritten (see point 1). Is there any other places? Files in `dev` that are more or less concepts and are never used by the plugin code?

Any way, thanks for all suggestions and I will definitely use most of them. If you can also elaborate a little bit more about point 5 and 6, it will helps a lot for me to better understand what and why is wrong.

**Comment by mkusz** [comment]
@bswck have you read my answers and request for more information about point 5 and 6? Without any more information from your side, I'm going to close this issue in next few days.

**Comment by mkusz** [comment]
Because there is no further communication with the author of this issue list, I'm closing it. My answers to raised questions/task:

1. I'm working on a new version of `pub-blog` plugin. Code will not have an `OrderedDict`.
2. Listed logging libraries are interesting but do not provide me with need functionality (like injecting code path). Adding external library increase dependency count and slightly extend installation time. I see no good reason to switch.
3. By using `typing.TYPE_CHECKING` code will not be formatted with `isort`. What's more, Python runtime is optimizing all import statements during code execution, so it's not a problem to import some files/classes just for types and type checking. This mechanism can be helpful whenever circular dependency occurs, but I this code, this didn't happen (so far).
4. A lot of `cast` is removed in an upcoming v2.0. Moreover, there are some clean-ups done here and there whenever I can see the need for that. Without pointing to any specific lines of code, I'm unable to determine what parenthesis are not needed. The issue is too general to fix something specific.
5. I have tested mentioned regexp code, and it works fast and reliable for word counting in blog posts. I don't see any reason why this solution could not be used, especially when it's used mostly to clean up text from not needed HTML code, symbols etc. Issue author didn't provide me with any alternative/better solution, so it's difficult to compare this solution to non-existing one.
6. In the upcoming v2.0 `importlib` is only used in internal library, so it seems like this issue is not longer a case.

Thanks for reporting those issues because I had to think about some code aspects and make some review by myself, but in the future, please add more detailed description to issue because points like 4, 5 and 6 are to generall.
